version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:10
    restart: always
    ports:
      - 35000:5432
    environment:
      - DB_USER=postgres
      - DB_PASS=admin